server:
  port: 8002


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.56.128:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Lxl19921121.

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

eureka:
  client:
    #是否从eureka注册中心抓取已经注册的服务，只有true，才能配合ribbon使用负载均衡
    fetch-registry: true
    #是否注册进注册中心
    register-with-eureka: true
    #注册中心地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
